QBShared.Items = {
    ['tabaco_weed'] = {
        ['name'] = 'tabaco_weed',
        ['label'] = '乾燥した煙草の葉',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'tabaco_weed.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '乾燥した煙草の葉だ',
    },
    ['rawpaper'] = {
        ['name'] = 'rawpaper',
        ['label'] = 'タバコの巻紙',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'rawpaper.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'タバコの巻紙 これで煙草の葉を包もう',
    },
    ['zippo'] = {
        ['name'] = 'zippo',
        ['label'] = 'ライター',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'zippo.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'これがあれば煙草に火をつけられる',
    },
    ['blackmoaicig'] = {
        ['name'] = 'blackmoaicig',
        ['label'] = 'タバコ',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'blackmoaicig.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'いい匂いだ',
    },
    ['cigarette'] = {
        ['name'] = 'cigarette',
        ['label'] = 'タバコ',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'cigarette.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'いい匂いだ',
    },
    ['yattimauzocig'] = {
        ['name'] = 'yattimauzocig',
        ['label'] = 'タバコ',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'yattimauzocig.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'いい匂いだ',
    },

    ['amoaia'] = {
        ['name'] = 'amoaia',
        ['label'] = 'αモアイA',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'amoaia.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '初心者用 ニコチン少なめ',
    },
    ['amoaii'] = {
        ['name'] = 'amoaii',
        ['label'] = 'αモアイI',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'amoaii.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '初心者用 ニコチン少なめ',
    },
    ['amoim'] = {
        ['name'] = 'amoim',
        ['label'] = 'αモアイM',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'amoim.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '初心者用 ニコチン少なめ',
    },
    ['blackmoai'] = {
        ['name'] = 'blackmoai',
        ['label'] = 'ブラックモアイ',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'blackmoai.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'レアな煙草,なかなか買えない',
    },
    ['butyomel'] = {
        ['name'] = 'butyomel',
        ['label'] = 'BUTYOMEL',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'butyomel.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'こくがある',
    },
    ['moaboro'] = {
        ['name'] = 'moaboro',
        ['label'] = 'モアボロ',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'moaboro.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'うまいけど,根本がもげやすい.',
    },
    ['moaisprit'] = {
        ['name'] = 'moaisprit',
        ['label'] = 'モアイスピリット',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'moaisprit.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '自然本来の匂いを楽しめる. オーガニックだから体にいい.',
    },
    ['rickstar'] = {
        ['name'] = 'rickstar',
        ['label'] = 'リックスター',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'rickstar.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = '警察はみんなこれを吸っているらしい',
    },
    ['yattimauzostar'] = {
        ['name'] = 'yattimauzostar',
        ['label'] = 'やっちまうぞスター',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'yattimauzostar.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'やっちまうぞ！！',
    },
    ['moaicigfood'] = {
        ['name'] = 'moaicigfood',
        ['label'] = 'モアイシガレット',
        ['weight'] = 10,
        ['type'] = 'item',
        ['image'] = 'moaicigfood.png',
        ['unique'] = false,
        ['useable'] = true,
        ['shouldClose'] = false,
        ['combinable'] = nil,
        ['description'] = 'ガキのお菓子',
    },

}